---
language: python
python:
  - "2.7"
  - "3.5"
env:
  global:
    - ANSIBLE_CONFIG=ansible.cfg
    - BUILD_DIR=build
    - BUILD=ansible-playbook-execute-${TRAVIS_BUILD_NUMBER}
  matrix:
    - ANSIBLE_VERSION=2.8.5
    - ANSIBLE_VERSION=2.9.2

before_install:
  - sudo apt-get update -qq
install:
  - pip install ansible==${ANSIBLE_VERSION}
before_script:
  - ansible --version
  - 'ansible-playbook -i controller.yml -e "{ clean: true, build_directory: ${BUILD_DIR}, build_number: ${TRAVIS_BUILD_NUMBER}, version: ${TRAVIS_TAG} }" build.yml'
  - cd "${BUILD_DIR}/${BUILD}"
  - |
    echo "
      executions:
      - label: env_a
        playbooks:
          - playbook.yml
        inventory:
          - inventory
        environment:
          ANSIBLE_STDOUT_CALLBACK: default
        extra_vars:
          - target_inventory: int,&node.1
        dependencies:
          - name: test-playbook-1
            type: ansible_playbook
            src:
              repo: https://github.com/theque5t/ansible-playbook-test-playbook-1.git
              version: v1.0.0
            src_type: git_repo
            version: 1.0.0
    " > executions.yml
script:
  - ansible-playbook -i controller.yml execute.yml --syntax-check
  - ansible-playbook -i controller.yml kill.yml --syntax-check
  - ansible-playbook -i controller.yml -e "@executions.yml" execute.yml
deploy:
  provider: releases
  api_key:
    secure: Im6tmR9hyCuHRL/MNcLwWnTOSh83HL3pEzyagbb8mNX5eC7lIMMyj9g9LJJwGNFCzJayOkz/PTyyT2RJ0vUe5xLuJxmBWFjnPgvqMbBjCN6jl30qTcyV0zJhcTALq0UC1kjf7s2iwPBchjV04izw3D1117jcpmO4A5/Rdjyf0Io5puMjYMHMzyRTUqrTYaMX408Zv4jyPflhlYLzxR/fRMsrMmbn72mWVeI/T1O7HwR4l8L1CdFb6P7uj6DTJvEc4gSvFPXzZxl5BnpZOLpydRCf23sguhB2gHI8NqPup1PulNuISf1lwrWzcpAP7yNDA8N6/rOv+KOZCUkVubg4tT5Cis2EXSAx7VDDhlxfwEI01nxQPxBJ0IghPc8wZsZD2PL96MffbUNmCW3m6k8OdoOoLtovwj3pq0vlfiMLc6fm/y/m1Sm3O6PKo5BtOfEL0m7NxaqAiJehdO49rx3MECHZTXiP94nRbKb8yjQzP9K0paSykH5TlgGqskfJFpQEAtfz33fAPSd0bd7dWLTuohmWfoqKq7kBfo0nTjta1QGuFTt03YxfHJGMj5i5R2r2QkSf2d7qiJdRRofvToNt6xji3Lnm8pWm4aa4rvJCpxTUBQuyTm6tAbJpauXXiFGl244FS4g9x9W5MVERQOki/vj5Qob3uHAM8xBp+/qnAUo=
  file_glob: true
  file:
    - "${BUILD_DIR}/*.tar.gz"
    - "${BUILD_DIR}/*.tar.gz.sha256"
  skip_cleanup: true
  draft: true
  on:
    repo: theque5t/ansible-playbook-execute
    tags: true
